# Generated by Django 6.0.6 on 2026-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_length_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('internal_width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('internal_height_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cost_rupees', models.PositiveIntegerField(help_text='Cost in rupees (e.g. 150 = INR 150)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cost_rupees'],
            },
        ),
    ]
